[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.0"
chrono = "0.4"

[profile.dev]
overflow-checks = false
opt-level = 3

[build]
rustflags = "-C target-cpu=native"