name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: chess/
        remote_host: 34.88.111.133
        remote_user: ing_hovind
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}        
    - name: gcp sync
      run: |
        mkdir ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        touch ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        ssh ing_hovind@34.88.111.133 /home/ing_hovind/.cargo/bin/cargo build --manifest-path /home/ing_hovind/chess/Cargo.toml
        ssh ing_hovind@34.88.111.133 sudo systemctl restart engine        
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
